### ISSUE TITLE
The game-premake/tree/no_edit link appears to be broken

### ISSUE THREAD

**Issue by RallyTronics** [raylib-extras/game-premake#10]
The https://github.com/raylib-extras/game-premake/tree/no_edit link gives me a 404.

**Comment by Peter0x44** [comment]
Seems like the branch was deleted. It got merged to master in https://github.com/raylib-extras/game-premake/pull/4
Don't see how this is an issue - if you want that, just use the current repo.

**Comment by RallyTronics** [comment]
It's an issue because the instructions in the readme direct the user to
`Download the game premake repository from https://github.com/raylib-extras/game-premake/tree/no_edit`

**Comment by Peter0x44** [comment]
This whole paragraph honestly needs some rewording tbh - I'll fix that, and also fix the link. Thanks for telling me.

**Comment by JeffM2501** [comment]
Thanks for finding and fixing this :)
