### ISSUE TITLE
Unresolved Externals

### ISSUE THREAD

**Issue by sabuka001** [raylib-extras/game-premake#15]
Hi! I'm getting a lot of unresolved externals errors whenever I add my own code in the visual studio premake. can you help?
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _InitWindow referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _WindowShouldClose referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _CloseWindow referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _ClearBackground referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _BeginDrawing referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _EndDrawing referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _SetTargetFPS referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _GetRandomValue referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _IsKeyDown referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _IsMouseButtonPressed referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _GetMousePosition referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _DrawRectangle referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _CheckCollisionRecs referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _DrawText referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK2019	unresolved external symbol _FormatText referenced in function _main	game game	D:\Algoritmika Projects\game game\_build\main.obj	1	
Error	LNK1120	15 unresolved externals	game game	D:\Algoritmika Projects\game game\_bin\Debug\game game.exe	1

**Comment by JeffM2501** [comment]
So what exact process did you use to add your code?
What you should do is this.

Delete the contents of _game/src_
add your own code to _game_ or _game/src_
re-run **premake-VisualStudio.bat**
Open the sln file in visual studio,
Do a **Rebuild Solution** from the _build_ menu in visual studio.

It sorta looks like you have some old files still in the build, so doing a rebuild will cleanup everything and start fresh.
