### ISSUE TITLE
Premake5 returning error with libc.so.6 / libm.so.6 older versions

### ISSUE THREAD

**Issue by AkrilaMayNotBeAvailable** [raylib-extras/game-premake#16]
Hello, I have been trying to use ./premake5 gmake2 to begin using premake at university PCs and currently I'm having a error since 2 days ago, it's has something to do with the version of libc and libm being outdated, I don't have ss at moment but it's like:

./premake5 gmake2
/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.29' not found
...
/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found`

We're using Raylib to learn how to code in C, and I prefer to use premake since it's far easier to run than linking raylib at some IDE aka{CB};
The thing is, I can't sudo and update those libraries, they usually do at end of each semester. Could I ask for a older version? Since it was working before the last update here.

**Comment by JeffM2501** [comment]
that sounds like your linux distro does not have the required version of libc that premake needs.

You can replace the premake5 with the current version from the website https://premake.github.io/download or see if your distro has a premake5 package.

if that doesn't work you'll have to get the libc version that premake wants from your package manager

**Comment by AkrilaMayNotBeAvailable** [comment]
Well, tried with the current version from the website, it still gives me the same error, but I managed to work with an older premake5 package I had around. Can't do much about libc version since I would need to update that linux distro and I don't have sudo access. Anyway it still works (yay) thanks Jeff.

**Comment by JeffM2501** [comment]
Yeah, that's one of my big issues with distros that lock down runtime versions, you can get locked out of newer software.

It does not matter what version of premake you use, so I'm glad it works  :)

**Comment by Peter0x44** [comment]
You could also build the newest premake yourself.
Download premake from https://github.com/premake/premake-core
then cd over there and run `make -f Bootstrap.mak linux`
