### ISSUE TITLE
Questions regarding building the game

### ISSUE THREAD

**Issue by msanatan** [raylib-extras/game-premake#18]
Hey, I'm using Raylib to learn more about C++ dev and really like this repo! I typically use VS Code for dev but I'm enjoying using VS for these kind of projects instead, and your template generates a solution automatically.

I have some questions regarding this setup:

1. How can I view the assets in my repo in VS? For example, I'd love to see the images + 3d model I have included at the side panel. If there's an option, can it be enabled by default? Or maybe a flag?
2. When I build it, the assets aren't bundled. I figure I'll have to add a copy step somewhere, any guidance here? Can this template be updated to copy resources automatically?
3. What typically happens when you want to release the game? Should I expect that VS' release option creates the right output? 
4. Any chance for CI/CD? Before trying out this  out I created my own template, it had GitHub actions for Windows, Mac and HTML5: https://github.com/msanatan/RaylibTemplate/blob/main/.github/workflows/ci.yml. What would be needed to have builds automoated?

**Comment by JeffM2501** [comment]
Ok there is a lot to unpack here so this response is going to be long.

Most of these questions seem to stem from an assumption that Visual Studio and Raylib is some kind of engine like Unity or Unreal. They are not. Your expectations for what game-premake, raylib, and visual studio do, do not seem correct.

1. Visual Studio is not a game editor. It is not like the editor in unity or unreal. It does not edit those kinds of assets. There is no flag or option to do that. There are options and extensions that you can install that will add external file type viewers to visual studio, but that's all extra. Take a look at your visual studio installer or extensions marketplace to see what else you can install to help with this. This is not something game-premake can help you with.

2. Raylib has no asset system, nor does it have a runtime resource system. There is no place to 'bundle' the assets too. Again Raylib is not an engine like unity or unreal. Visual Studio and Game-Premake don't know what your assets are, where they should go, or what kind of runtime resource system you are going to use. Visual studio does not compile or process your assets in any way, it doesn't even care if they are in the project or not. Assets/Resources are read at runtime by raylib, not at compile time. All this is WAY outside the scope of raylib. You are expected to implement your own runtime resource system. There are libs you can use to help such as rres and others, but this is all up to you. There is no one stop resource system that we could include/force everyone to use. Each game has its own unique requirements. Again this is on you, not game premake or visual studio to do automatically.

3. What you do on release is up to you and how you want to package your game. Visual Studio does not package your game up into a distribution package. The release build just builds an exe that does not have debug info and is targeted to run on computers that don't have Visual Studio. Visual Studio and Raylib are not an engine like Unity, you do not 'export' your game. You have many options available to you, but all of them involve you creating your release workflow on your own.
     a. Just zip up the game exe and your resources folder, let your game read loose files.
     b. Use a package system like rres or a zip file
     c. Create an asset pipeline and tooling that encodes your resources as code and builds them into your game as C/C++ sources. (https://youtu.be/6l4S7bexGtg)
     d. Some other system that is up to you.

4. Build automation and CI/CD would be outside the scope of raylib and game-premake, it would be specific to your game, your tests and use your automation platform (github actions if that's what you are using).

It seems like you have an incorrect expectation of what Visual Studio and raylib are, they are not a game engine or a game creation system. 

Raylib is a fairly low-level game development framework that is designed to help people learn how to make games or game like things. It is intended for people who want to learn how games and engines are made at a low level.  Raylib is not designed to be a professional game engine out of the box, it can be part of one but only if you put in a lot of work to make it be one.

Visual Studio is not a game editor, it is a generic IDE for software development in many languages. It doesn't know you are making a game. 

Game-Premake is a cross platform system that helps people setup very basic VSProjects and makefiles for raylib. Game-Premake is not focused on just visual studio development. It's goal is to help get people started using and learning with raylib.

Raylib and Visual Studio can be part of a system that does all the things you describe, but they are going to be specific to your game and require you to do a lot of work to get those pipelines setup. There are many different ways that games can be made and game-premake cannot pick one of those for you and implement it.  Also the maintenance cost of doing that would be prohibitive and error prone for me.

Raylib doesn't provide an asset pipeline, one of the things you are expected to learn using raylib is how to develop an asset pipeline. Raylib just knows how to read the data you feed it, that's it, it doesn't care where it comes from. It's your job to create a system that feeds the data you need into raylib.

Raylib isn't a platform, it's a library that helps you out. Unlike an engine that would run your game code, with a raylib project your code is in charge. Your code is what creates the application, and your code is what asks raylib to do things. So your code has all the responsibilities, and that means you have the responsibility to manage all the data.

**Comment by msanatan** [comment]
Hmm... I'm aware of what Rayib is and isn't, as well as the differences between library and an "engine". The questions are more to do with what's offered when starting a project using this VS build configuration, and seeing if we can get more out of it.

Generating a game with premake and running in Visual Studio, the game resources are loaded correctly. As a user, I'd expect the default build action for releases would be to copy resources referenced in the game. When testing my game based off this premake build configuration - the models were not copied and I saw white cubes - the placeholder raylib adds when a model can't be loaded. 

It's fine. I'll modify the release config to copy the resource folder + look into VS to see if I can list the resources folder in my solution viewer. But copying resources does seem like a sensible configuration if you're generating a VS Solution.

Thanks for clarifying the CI/CD options, and that it's out of scope. I'll use my existing workflows for Raylib projects.

**Comment by msanatan** [comment]
> Some options are:
> 
> 1. you add a post build step to copy the exe to the rot, so it's in the same place as the resources dir. I do not do this by default because that may not be where someone wants to publish. too.
> 2. you add a post build step to copy the resource folder into the bin dir so that again the exe is in the same folder as the resources dir. I do not do this because it's dumb and duplicates too much data, and may not be what a user wants.
> 3. use some code in your game to find the resources dir and set the working dir so that relative paths work from many locations. Example code is here https://github.com/raylib-extras/extras-c/blob/main/path_utils/resource_dir.h . I do not do this by default, again because that may not be what someone wants to do.
> 
> Setting the working directory to the correct value for your asset pipeline is one of the things you have to learn using raylib.

That's fine, the configurations generated aren't opinionated by design.

> The release build target is not a publishing process, it is simply a build target, it just removes debug info. Publishing, packaging, and setting up for running outside the dev environment is entirely on you, it is not something that game-premake can do for you.

I'm aware, and cool, you  rather not be opinionated on how this is done either.

All good, cheers.
