### ISSUE TITLE
No X11/xlib.h found fatal error when compiling

### ISSUE THREAD

**Issue by XenoBenn** [raylib-extras/game-premake#22]
I'm following [this](https://www.youtube.com/watch?v=--gI9083QnU) tutorial. Using freshly installed WSL ubuntu and when I am at the point to build it with the make command I get this error:
```
../raylib-master/src/external/glfw/src/x11_platform.h:32:10: fatal error: X11/Xlib.h: No such file or directory
   32 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
If I understand correctly, I should have this folder right?

**Comment by JeffM2501** [comment]
Wsl does not come with x11 by default, you need to install the dev packages for it. https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

This is not a game-premake issue. The tutorial assumes that when building on Linux you are on a real Linux desktop system, not the subset of Linux that wsl defaults to. 

If you are trying to build on windows it is better to use the w64devkit and build for native windows than to build and run a Linux version in the wsl virtual machine.

**Comment by Peter0x44** [comment]
To obtain the headers, there are -dev(el) packages you need to install.
They are documented here:
https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux#install-required-libraries
