### ISSUE TITLE
mingw32-make: No rule to make target "../bin/Debug/raylib.lib"

### ISSUE THREAD

**Issue by PreetomBoro** [raylib-extras/game-premake#27]
I used mingw32-make to build the game, but it seems to throw some error.
![image](https://github.com/raylib-extras/game-premake/assets/167507439/0887b77a-d49d-4f78-8c1e-910abc7abece)

(I already had msys2 MinGW-w64-ucrt toolchain so I didn't install the suggested compiler.)

**Comment by Peter0x44** [comment]
Why don't you build from msys2 's UCRT64 shell instead of cmd then?
Does it work then?

**Comment by Peter0x44** [comment]
Also, the output of `verbose=1 make` would be better.

**Comment by PreetomBoro** [comment]
@Peter0x44 command prompt just feels cozy(I know very bad excuse, but I mostly use msys terminal to only download toolchain packages). 
no it doesn't work in the ucrt terminal either:
![image](https://github.com/raylib-extras/game-premake/assets/167507439/9f1a031d-d372-4c36-9708-fc3a1bbc1492)

**Comment by PreetomBoro** [comment]
verbose=1 is giving the same output
![image](https://github.com/raylib-extras/game-premake/assets/167507439/a701862c-4169-49bd-9b48-2117a99b7fba)

**Comment by Peter0x44** [comment]
msys2 works on my machine:
```
UCRT64 ~/game-premake
$ ./premake5.exe gmake2
Raylib not found, downloading from github
Unzipping to C:/msys64/home/Peter/game-premake
Using raylib dir raylib-master
game
Building configurations...
Running action 'gmake2'...
Generated Makefile...
Generated raylib-master/Makefile...
Generated game/Makefile...
Done (21737ms).

UCRT64 ~/game-premake
$ make
==== Building raylib (debug_x64) ====
Creating obj/x64/Debug
raudio.c
In file included from src/raudio.c:270:
src/external/jar_xm.h:242: warning: "DEBUG" redefined
  242 | #define DEBUG(...)
      |
<command-line>: note: this is the location of the previous definition
rcore.c
In file included from src/rcore.c:114:
src/rlgl.h: In function 'rlSetVertexAttribute':
src/rlgl.h:3948:70: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 3948 |     glVertexAttribPointer(index, compSize, type, normalized, stride, (void *)offset);
      |                                                                      ^
rglfw.c
rmodels.c
rshapes.c
rtext.c
rtextures.c
utils.c
Creating ../bin/Debug
Linking raylib
==== Building game-premake (debug_x64) ====
Creating obj/x64/Debug
raylib_game.c
screen_ending.c
screen_gameplay.c
screen_logo.c
screen_options.c
screen_title.c
Linking game-premake
```
I cannot reproduce.

I don't recommend msys2 if you are simply using it to obtain a toolchain for use with raylib.
w64devkit suits that usage far better:
https://github.com/skeeto/w64devkit/releases/latest

**Comment by PreetomBoro** [comment]
thank you for the suggestion. I'll delete the whole project and try from beginning once more with just msys terminal and will let you know if it works.

**Comment by PreetomBoro** [comment]
btw, here is the output when I tried --trace argument:
`ASUS@LAPTOP-8K8ERLAF UCRT64 /e/ExperimentCpp/raylibproject1/game
$ mingw32-make.exe --trace
Makefile:146: update target 'obj/x64/Debug' due to: target does not exist
echo Creating obj/x64/Debug
Creating obj/x64/Debug
mkdir -p obj/x64/Debug
Makefile:166: update target 'prebuild' due to: target is .PHONY
Makefile:188: update target 'obj/x64/Debug/raylib_game.o' due to: target does not exist
echo "raylib_game.c"
raylib_game.c
cc   -MD -MP -DDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32 -I. -Isrc -Iinclude -I../r
aylib-master/src -I../raylib-master/src/external -I../raylib-master/src/external/glfw/include -m64 -
g -std=c99  -o "obj/x64/Debug/raylib_game.o" -MF "obj/x64/Debug/raylib_game.d" -c "src/raylib_game.c
"
Makefile:191: update target 'obj/x64/Debug/screen_ending.o' due to: target does not exist
echo "screen_ending.c"
screen_ending.c
cc   -MD -MP -DDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32 -I. -Isrc -Iinclude -I../r
aylib-master/src -I../raylib-master/src/external -I../raylib-master/src/external/glfw/include -m64 -
g -std=c99  -o "obj/x64/Debug/screen_ending.o" -MF "obj/x64/Debug/screen_ending.d" -c "src/screen_en
ding.c"
Makefile:194: update target 'obj/x64/Debug/screen_gameplay.o' due to: target does not exist
echo "screen_gameplay.c"
screen_gameplay.c
cc   -MD -MP -DDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32 -I. -Isrc -Iinclude -I../r
aylib-master/src -I../raylib-master/src/external -I../raylib-master/src/external/glfw/include -m64 -
g -std=c99  -o "obj/x64/Debug/screen_gameplay.o" -MF "obj/x64/Debug/screen_gameplay.d" -c "src/scree
n_gameplay.c"
Makefile:197: update target 'obj/x64/Debug/screen_logo.o' due to: target does not exist
echo "screen_logo.c"
screen_logo.c
cc   -MD -MP -DDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32 -I. -Isrc -Iinclude -I../r
aylib-master/src -I../raylib-master/src/external -I../raylib-master/src/external/glfw/include -m64 -
g -std=c99  -o "obj/x64/Debug/screen_logo.o" -MF "obj/x64/Debug/screen_logo.d" -c "src/screen_logo.c
"
Makefile:200: update target 'obj/x64/Debug/screen_options.o' due to: target does not exist
echo "screen_options.c"
screen_options.c
cc   -MD -MP -DDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32 -I. -Isrc -Iinclude -I../r
aylib-master/src -I../raylib-master/src/external -I../raylib-master/src/external/glfw/include -m64 -
g -std=c99  -o "obj/x64/Debug/screen_options.o" -MF "obj/x64/Debug/screen_options.d" -c "src/screen_
options.c"
Makefile:203: update target 'obj/x64/Debug/screen_title.o' due to: target does not exist
echo "screen_title.c"
screen_title.c
cc   -MD -MP -DDEBUG -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -D_WIN32 -I. -Isrc -Iinclude -I../r
aylib-master/src -I../raylib-master/src/external -I../raylib-master/src/external/glfw/include -m64 -
g -std=c99  -o "obj/x64/Debug/screen_title.o" -MF "obj/x64/Debug/screen_title.d" -c "src/screen_titl
e.c"
mingw32-make: *** No rule to make target '../bin/Debug/raylib.lib', needed by '../bin/Debug/raylibpr
oject1.exe'.  Stop.
`

**Comment by PreetomBoro** [comment]
@Peter0x44 it worked on the ucrt terminal (idk what's wrong with command prompt)
![image](https://github.com/raylib-extras/game-premake/assets/167507439/2158c768-6f1f-47ec-be1a-109d5ae0d1ab)
![image](https://github.com/raylib-extras/game-premake/assets/167507439/b9ce5068-a94b-4fef-9487-3cbdd7656954)
