### ISSUE TITLE
'premake5' command not found when building on Ubuntu

### ISSUE THREAD

**Issue by ethanfischer** [raylib-extras/game-premake#6]
Hi,

After following the instructions, I'm getting the error message "bash: ./premake5: No such file or directory" when running the command `./premake5 gmake2` after cd'ing into the game directory. I tried doing this in a few different directories but always with the same result.

**Comment by ethanfischer** [comment]
Figured it out as I was typing this. I had to go to the premake5 file > right click it > properties > permissions > check 'Allow executing file as program'

**Comment by Peter0x44** [comment]
Perhaps the permissions of the premake5 binary in the repo should be updated? Then it would be executable when you cloned it, no need to give it executable permissions explicitly.
